- .github/workflows/git-action.yml
feat/#4  → dev
프론트 workflows 파일 접속 포트 3000 -> 80으로 수정하였습니다.
close #4 
PR이 다음 요구 사항을 충족하는지 확인하세요.
> chore: workflows git-action.yml 포트 수정

- public/sw.js
- src/app/user/page.tsx
- src/auth.ts
- src/types/next-auth.d.ts
- src/types/userType.ts
(feat/#21)  → (dev)
- 로그인 API 연결
[#21 ] - (close)
(참고사항을 적어주세요)
> feat:로그인 API 연결

- src/hooks/usePayment.ts
(feat/#97)  → (dev)
env파일까지 수정했는데 저번에 얘가 인식을 못해서 제가 분리를 안했었는데
깜빡하고 다시 분리했네요 ㅠㅜㅠ
[#(97)] - (close)
(참고사항을 적어주세요)
> fix: 결제 key 다시 코드로 수정

- src/app/user/mypage/layout.tsx
- src/app/user/mypage/likelist/page.tsx
- src/components/pages/auth/signUp/preferredStyle/PreferredStyle.tsx
- src/components/pages/user/reqCoordi/ReqListContents.tsx
- src/components/ui/skeleton.tsx
- src/libs/myPageTitleMap.ts
- src/libs/styleData.ts
- src/types/titleMapType.ts
(feat/#117)  → (dev)
- 요청서, 좋아요, 팔로우 데이터 예외처리
[#117] - (close)
PR이 다음 요구 사항을 충족하는지 확인하세요.
> feat: 요청서, 좋아요, 팔로우 데이터 예외처리

- src/app/user/coordinator/[partnerId]/profile/@tabs/review/page.tsx
(feat/#115)  → (dev)
[#(115)] - (close)
(참고사항을 적어주세요)
> feat: 유저 리뷰 컴포넌트 추가

- src/components/pages/partner/profile/PartnerProfileTopInfo.tsx
(feat/#115)  → (dev)
코디 매칭, 팔로워 수 오류 수정
(참고사항을 적어주세요)
> fix: 팔로워수 오류 수정

- src/app/user/mypage/followlist/page.tsx
- src/components/pages/member/home/HomeEventSection.tsx
- src/components/pages/member/home/HomePartnerPost.tsx
- src/components/pages/member/home/HomePartnerPosts.tsx
- src/components/pages/member/home/HomeTipSection.tsx
(feat/#121)  → (dev)
- 데이터 예외 처리 및 홈 화면 섹션 제목 에러 수정
[#121] - (close)
(참고사항을 적어주세요)
> feat: 데이터 예외 처리 및 홈화면 섹션 제목 에러 수정

- src/components/pages/auth/signIn/SignInForm.tsx
- src/components/pages/member/profile/FavoriteStyleList.tsx
(fix/#125)  → (dev)
- 로그인 시 role이 있는 경우 해당 role 경로로 이동하도록 수정
- 파트너 프로필 스타일 선택 bottom 공간 추가
[#(125)] - (close)
(참고사항을 적어주세요)
> fix: 로그인 라우팅 및 스타일 css 수정

- src/components/pages/auth/signIn/SignInForm.tsx
(fix/#125)  → (dev)
로그인 컴포넌트 localStorage 접근 에러 수정
(참고사항을 적어주세요)
> fix: localstorage 접근 에러 수정

- src/actions/member/Auth.ts
- src/actions/user/UserHome.ts
- src/app/(common)/(auth)/signup/page.tsx
- src/app/user/(home)/page.tsx
- src/components/pages/auth/signUp/SignUpFunnel.tsx
- src/components/pages/auth/signUp/birthAndGender/UserBirthAndGender.tsx
- src/components/pages/auth/signUp/id/UserId.tsx
- src/components/pages/auth/signUp/name/UserName.tsx
- src/components/pages/auth/signUp/preferredStyle/PreferredStyle.tsx
- src/components/pages/member/home/HomePartnerPost.tsx
- src/components/pages/member/home/HomePartnerPosts.tsx
- src/components/pages/member/home/HomeRecommendStyle.tsx
- src/components/pages/member/home/HomeSectionTitle.tsx
- src/components/pages/member/home/HomeTipSection.tsx
- src/components/pages/member/home/RecommendStyleSwiper.tsx
(fix/#124)  → (dev)
- 파트너 프로필 이미지 url이 null인 경우 에러 처리 
- 회원가입 시 스타일 선택 화면 스켈레톤 적용
[#124] - (close)
(참고사항을 적어주세요)
> fix: 파트너 프로필 이미지 url이 null인 경우 에러 처리 및 회원가입 시 스타일 선택 화면 스켈레톤 적용

- src/app/(common)/ranking/page.tsx
- src/app/api/auth/[...nextauth]/options.ts
- src/app/layout.tsx
- src/app/user/mypage/reviewlist/page.tsx
- src/components/common/UnderConstruction.tsx
- src/components/pages/auth/signIn/SignInForm.tsx
- src/components/provider/ExpiredProvider.tsx
- src/types/next-auth.d.ts
(fix/#130)  → (dev)
- 토큰 만료 시 자동 로그아웃 처리
- 마이페이지에서 파트너 로그인 시 user/mypage로 이동하는 오류 수정
-> 이거 이렇게 해도되나싶긴한데....억지로 억지로...일단 추가했습니다...ㅠ 더 좋은 방법 찾아봐야할 것 같아요.
- 랭킹페이지 하단 마진 추가
[#(130)] - (keyword)
(참고사항을 적어주세요)
> fix: 세션 만료 시 자동 로그아웃 및 라우팅 수정

- src/actions/member/Auth.ts
- src/app/(common)/(auth)/signup/page.tsx
- src/components/pages/auth/signUp/SignUpFunnel.tsx
- src/components/pages/auth/signUp/birthAndGender/UserBirthAndGender.tsx
- src/components/pages/auth/signUp/id/UserId.tsx
- src/components/pages/auth/signUp/preferredStyle/PreferredStyle.tsx
- src/components/pages/member/home/HomePartnerPost.tsx
- src/components/pages/member/home/HomePartnerPosts.tsx
(fix/#129)  → (dev)
- 회원 가입 시 성별 값 수정
- 선호스타일 선택 부분 스켈레톤 제거 (의심되는 부분이라 배포 후 확인할 예정입니다. -> 로컬에서는 문제가 없어요..ㅠㅠ)
[#129] - (close)
(참고사항을 적어주세요)
> fix: 회원가입 시 성별 값 수정 및 선호스타일 선택 부분 스켈레톤 제거

- src/components/pages/member/home/RecommendStyleSwiper.tsx
(fix/#135)  → (dev)
- 홈화면 추천 스타일 프로필 이미지 크기 수정
[#135] - (close)
(참고사항을 적어주세요)
> fix: 홈화면 추천 스타일 프로필 이미지 크기 수정

- src/actions/partner/PartnerPost.ts
- src/app/user/(home)/page.tsx
(fix/#138)  → (dev)
[#(138)] - (keyword)
(참고사항을 적어주세요)
> fix: 포스팅 캐시 수정

- src/components/pages/partner/reqCoordi/RequestInformation.tsx
(branch)  → (branch)
(참고사항을 적어주세요)
> fix: 파트너 요청서 조회 옵션 수정

- src/utils/getCurrentStep.ts
(branch)  → (branch)
(참고사항을 적어주세요)
> fix: step 상태 수정

- src/components/pages/chats/box/PartnerChatBoxButton.tsx
(fix/#143)  → (dev)
-상태관리로 인한 채팅방 매칭 이슈로 원래대로 돌림
(참고사항을 적어주세요)
> fix: 파트너 채팅방 정보 로직 수정

- src/app/error.tsx
- src/components/pages/partner/profile/PartnerCareerBox.tsx
- src/components/pages/partner/profile/PartnerChatTimeAndLeadTimeBox.tsx
- src/components/pages/partner/profile/PartnerSnsBox.tsx
(fix/#145)  → (dev)
(참고사항을 적어주세요)
> fix: 파트너 프로필 정보없음 추가

- src/components/pages/auth/signUp/id/UserId.tsx
(fix/#150)  → (dev)
- 회원가입 이메일 검증 로직 수정
[#150] - (close)
(참고사항을 적어주세요)
> fix: 회원가입 이메일 검증 로직 수정

- src/components/ui/button/CoordiRequestButton.tsx
- src/components/ui/tabs/PartnerProfileTabs.tsx
(fix/#152)  → (dev)
파트너 프로필 스타일 수정
[#(152)] - (close)
PR이 다음 요구 사항을 충족하는지 확인하세요.
> fix: 파트너 프로필 z-index 수정

- src/components/pages/chats/Message.tsx
(fix/#154)  → (dev)
카드 전송 후 한번 더 생성되는 현상 수정
[#(154)] - (close)
(참고사항을 적어주세요)
> fix: 채팅방 로직 수정
